
Linear Algebra Operators

+, -, *, ×(cross), ⋅ (inner product), norm, transpose, box product, inverse, det, cofactor, power series, exponential, pseudo-inverse


In [2]:
## Import packages
import numpy as np


---
Basic operation


In [3]:
A = np.array([[1, 2, 3], [1, 1, 1], [3, 2, 1]])
B = np.array([[2, 1, 2,], [1, 2, 4], [2, 1, 0]])
print(A)
print(B)

[[1 2 3]
 [1 1 1]
 [3 2 1]]
[[2 1 2]
 [1 2 4]
 [2 1 0]]


In [4]:
A+B

array([[3, 3, 5],
       [2, 3, 5],
       [5, 3, 1]])

In [5]:
A-B

array([[-1,  1,  1],
       [ 0, -1, -3],
       [ 1,  1,  1]])

In [6]:
A*B

array([[2, 2, 6],
       [1, 2, 4],
       [6, 2, 0]])

In [7]:
A@B

array([[10,  8, 10],
       [ 5,  4,  6],
       [10,  8, 14]])

In [8]:
np.matmul(A,B)

array([[10,  8, 10],
       [ 5,  4,  6],
       [10,  8, 14]])

In [9]:
u = np.array([1,2,3])
v = np.array([2,4,5])

In [10]:
u

array([1, 2, 3])

In [11]:
np.cross(u,v)

array([-2,  1,  0])

In [12]:
np.inner(u,v)

np.int64(25)

In [13]:
np.dot(u,v)

np.int64(25)

In [14]:
# np.linalg.norm(u)
np.linalg.norm(v)

np.float64(6.708203932499369)

In [15]:
# A.T
np.transpose(A)

array([[1, 1, 3],
       [2, 1, 2],
       [3, 1, 1]])

In [16]:
w = np.array([4, 2, 3,])

In [17]:
np.dot(np.cross(u,v), w)

np.int64(-6)

In [18]:
A

array([[1, 2, 3],
       [1, 1, 1],
       [3, 2, 1]])

In [19]:
A**(0.5) # elementwise multiplication

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.        , 1.        ],
       [1.73205081, 1.41421356, 1.        ]])

In [20]:
A^(2)  ## bit xor operator

array([[3, 0, 1],
       [3, 3, 3],
       [1, 0, 3]])

In [21]:
np.linalg.matrix_power(A, 3)

array([[46, 50, 54],
       [25, 25, 25],
       [54, 50, 46]])

In [22]:
A@A

array([[12, 10,  8],
       [ 5,  5,  5],
       [ 8, 10, 12]])

In [23]:
np.linalg.det(B)

np.float64(-6.0)

In [24]:
np.linalg.inv(B)

array([[ 0.66666667, -0.33333333,  0.        ],
       [-1.33333333,  0.66666667,  1.        ],
       [ 0.5       , -0.        , -0.5       ]])

In [25]:
np.linalg.pinv(B)

array([[ 6.66666667e-01, -3.33333333e-01, -1.69295099e-16],
       [-1.33333333e+00,  6.66666667e-01,  1.00000000e+00],
       [ 5.00000000e-01, -1.17957412e-16, -5.00000000e-01]])

In [26]:
# np.linalg.inv(B)
np.linalg.pinv(B)

array([[ 6.66666667e-01, -3.33333333e-01, -1.69295099e-16],
       [-1.33333333e+00,  6.66666667e-01,  1.00000000e+00],
       [ 5.00000000e-01, -1.17957412e-16, -5.00000000e-01]])



---

Functions for programming

In [27]:
A = np.array([[2, 1, 2,], [1, 2, 4], [2, 1, 0]])
print(A)

[[2 1 2]
 [1 2 4]
 [2 1 0]]


In [28]:
index = 1
axis = 0 # axis 0: row, axis 1: column
np.delete(A, index, axis)

array([[2, 1, 2],
       [2, 1, 0]])

In [29]:
index = 2
adding = [3, 4, 5]
axis = 0
np.insert(A, index, adding, axis)


array([[2, 1, 2],
       [1, 2, 4],
       [3, 4, 5],
       [2, 1, 0]])

In [30]:
adding = [[3, 4, 5]]
axis = 0
np.append(A, adding, axis) # add at the end

array([[2, 1, 2],
       [1, 2, 4],
       [2, 1, 0],
       [3, 4, 5]])

In [31]:
A = np.random.rand(4,8)
# print(A)
# new_row =
# new_column = 10
# np.reshape(A, (new_row, new_column))
np.reshape(A, (32, -1))

array([[0.52008013],
       [0.60467578],
       [0.04070136],
       [0.70147833],
       [0.81034003],
       [0.55705537],
       [0.01240167],
       [0.5408537 ],
       [0.6013392 ],
       [0.31318466],
       [0.80214049],
       [0.02680557],
       [0.15395625],
       [0.34528541],
       [0.41951821],
       [0.62851728],
       [0.02791284],
       [0.5050467 ],
       [0.91424232],
       [0.25337642],
       [0.67371445],
       [0.85137578],
       [0.16177132],
       [0.44471971],
       [0.7385492 ],
       [0.98504042],
       [0.18584213],
       [0.9757356 ],
       [0.55227894],
       [0.88618929],
       [0.76890057],
       [0.05988714]])

In [ ]:
u = np.array([1,2,3])
v = np.array([2,4,5])
w = np.array([7,2,4])
A = np.array([[1, 2, 3], [1, 1, 1], [3, 2, 1]])
print(A)

[[1 2 3]
 [1 1 1]
 [3 2 1]]


In [ ]:
np.vstack([u, v, w])
np.vstack([A,A])

array([[1, 2, 3],
       [1, 1, 1],
       [3, 2, 1],
       [1, 2, 3],
       [1, 1, 1],
       [3, 2, 1]])

In [ ]:
np.hstack([u, v, w])
np.hstack([A,A])

array([[1, 2, 3, 1, 2, 3],
       [1, 1, 1, 1, 1, 1],
       [3, 2, 1, 3, 2, 1]])

In [ ]:
print(A)
B = np.split(A, 4, axis =0)
print(B)

[[0.44055405 0.88801391 0.65794873 0.36839062 0.26933152 0.71923007
  0.22505143 0.12914139]
 [0.44149255 0.11050333 0.61573876 0.37037778 0.5529465  0.27948537
  0.60874659 0.17896623]
 [0.15826059 0.75056353 0.83239035 0.86087358 0.91964022 0.16603906
  0.37070881 0.69188932]
 [0.01798089 0.84474823 0.50939684 0.29203184 0.85709922 0.21194868
  0.50637138 0.78839887]]
[array([[0.44055405, 0.88801391, 0.65794873, 0.36839062, 0.26933152,
        0.71923007, 0.22505143, 0.12914139]]), array([[0.44149255, 0.11050333, 0.61573876, 0.37037778, 0.5529465 ,
        0.27948537, 0.60874659, 0.17896623]]), array([[0.15826059, 0.75056353, 0.83239035, 0.86087358, 0.91964022,
        0.16603906, 0.37070881, 0.69188932]]), array([[0.01798089, 0.84474823, 0.50939684, 0.29203184, 0.85709922,
        0.21194868, 0.50637138, 0.78839887]])]


In [ ]:
np.triu(A) # upper triangular

In [ ]:
np.tril(A) # lower triangular

array([[0.44055405, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.44149255, 0.11050333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.15826059, 0.75056353, 0.83239035, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.01798089, 0.84474823, 0.50939684, 0.29203184, 0.        ,
        0.        , 0.        , 0.        ]])

In [ ]:
print(A)

[[1 2 3]
 [1 1 1]
 [3 2 1]]


In [ ]:
np.where(A>1, A, 0)

array([[0, 2, 3],
       [0, 0, 0],
       [3, 2, 0]])

In [ ]:
A = np.array([[1, 2, 3], [1, 1, 1], [3, 2, 1]])
B = np.array([[2, 1, 2,], [1, 2, 4], [2, 1, 0]])

In [ ]:
# np.wehre(condition, A, B)
np.where(A>1, B, 0)
np.where(A>1, A, B)

array([[2, 2, 3],
       [1, 2, 4],
       [3, 2, 0]])

In [ ]:
n_row, n_col = A.shape
print(n_row, n_col)

3 3


In [ ]:
A.size

9

In [ ]:
A.ndim

2

In [ ]:
A.flatten()

array([1, 2, 3, 1, 1, 1, 3, 2, 1])

In [ ]:
B = np.expand_dims(B, axis=0)
print(B.shape)

(1, 1, 1, 1, 1, 1, 3, 3)


In [ ]:
B = np.expand_dims(B, axis = 2)

In [ ]:
B =np.squeeze(B)

In [ ]:
B.shape

(3, 3)

In [ ]:
print(A)

[[1 2 3]
 [1 1 1]
 [3 2 1]]


In [ ]:
# A[0:2]
A[1][1]

np.int64(1)

In [ ]:
# A[-1,2]
A[:,2]

array([3, 1, 1])

In [ ]:
np.sum(A, axis = 0)

In [ ]:
np.zeros((1,2,1))

In [ ]:
np.diag([3,5,2], 0)

---
Minor, Cofactor, Adjoint matrix


In [ ]:
A = np.array([[2, 4, 1,], [3, 1, 1], [1, 2, 1]])
print(A)

[[2 4 1]
 [3 1 1]
 [1 2 1]]


In [ ]:
def reduce_matrix(matrix, i,j):
  new_matrix = np.delete(matrix, i, 0)
  new_matrix = np.delete(new_matrix, j, 1)
  return new_matrix

In [ ]:
cofactor_matrix = np.zeros_like(A, float)

for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    minor = np.linalg.det(reduce_matrix(A, i,j))
    cofactor = ((-1)**(i+j))*minor
    cofactor_matrix[i,j] = cofactor

print(cofactor_matrix)

[[ -1.  -2.   5.]
 [ -2.   1.  -0.]
 [  3.   1. -10.]]


In [ ]:
adjoint_matrix = cofactor_matrix.T
inverse_matrix = 1/np.linalg.det(A) * adjoint_matrix
print(inverse_matrix)
print(np.linalg.inv(A))

[[ 0.2  0.4 -0.6]
 [ 0.4 -0.2 -0.2]
 [-1.   0.   2. ]]
[[ 0.2  0.4 -0.6]
 [ 0.4 -0.2 -0.2]
 [-1.   0.   2. ]]
